name: tugas_mp1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Google.webp
    - assets/images/Logo.png
    - assets/images/aki.jpg
    - assets/images/busi.jpg
    - assets/images/filter.jpg
    - assets/images/Kampas.jpeg
    - assets/images/oli.jpeg
    - assets/images/rantei.jpeg
    - assets/images/suzuki.png
    - assets/images/yamaha.png
    - assets/images/lainnya.png
    - assets/images/Honda.jpeg
    - assets/images/logohonda.png
    - assets/images/banner.jpg
    - assets/images/welcome1.png
    - assets/images/welcome2.png
    - assets/images/welcome3.png
    - assets/images/login.jpg
    - assets/images/backgroun.jpg
    - assets/images/wiwok.jpg
    - assets/images/detok.jpg
    - assets/images/testt.jpg
    - assets/images/biru.jpg
